#pragma once

#include <string>
#include <unordered_map>

const int cellWidth = 96;
const int cellHeight = 96;
const int cellSize = 96;

const int levelsInStage = 6;

const float basePlayerMAlength = 0.2f;

enum MenuElementType
{
    ME_BUTTON,
    ME_TEXT,
    ME_SLIDER,
    ME_SWITCH,
    ME_SELECTION,
    ME_PICTURE
};

enum MenuSelectionMarkerType
{
    SM_LINE,
    SM_ARROW
};

enum MenuSceneName
{
    SCENE_MAIN_MENU,
    SCENE_PLAY,
    SCENE_SAVES,
    SCENE_USER_LEVELS,
    SCENE_OPTIONS,
    SCENE_VIDEO,
    SCENE_CONTROLS
};

enum Direction
{
    NO_DIRECTION = -1,
    UP,
    RIGHT,
    DOWN,
    LEFT
};

void rotate_direction(Direction &dir, int t);

enum DamageType
{
    D_PHYSICAL,
    D_AIR,
    D_EARTH,
    D_FIRE,
    D_WATER,
    D_HOLY,
    D_DEMONIC
};

enum MobName
{
    M_BARBARIAN,
    M_WIZARD,
    M_PALADIN,
    M_ZOMBIE,
    M_LICH,
    M_WRAITH
};

enum MobType
{
    M_SMALL,
    M_MEDIUM,
    M_LARGE,
    M_BOSS
};

enum MobAction
{
    M_IDLE,
    M_MOVING,
    M_ATTACKING,
    M_CASTING_BOLT,
    M_CASTING_ERUPTION,
    M_CASTING_SLOW,
    M_CHARGING,
    M_BLOCKING,
    M_RAISING_ZOMBIE
};

enum PlayerAction
{
    P_IDLE,
    P_MOVING
};

const std::string action_strings[9] =
{
    "idle",
    "moving",
    "attacking",
    "casting_bolt",
    "casting_eruption",
    "casting_slow",
    "charging",
    "blocking",
    "raising_zombie"
};

std::string action_string(int ma);

enum TileType
{
    WALL,
    BASE_FLOOR,
    FLOOR,
    WATER,
    LAVA
};

enum TileVariant
{
    V_STONE,
    V_DIRT
};

enum LevelType
{
    NEW_GAME,
    SAVE,
    USER
};

enum SpriteName
{
    // Blocks
    DIRT,
    STONE,
    STONE_SIDE,
    EXIT_GREEN,
    WATER_1,
    WATER_2,
    WATER_3,
    LAVA_1,
    LAVA_2,
    LAVA_3,

    // Entities
    WIZARD_BOLT_UP,
    WIZARD_BOLT_DOWN,
    WIZARD_BOLT_LEFT,
    WIZARD_BOLT_RIGHT,

    LICH_BOLT_UP,
    LICH_BOLT_DOWN,
    LICH_BOLT_LEFT,
    LICH_BOLT_RIGHT,

    GOLD_1,
    GOLD_2,
    GOLD_3,
    GOLD_4,
    GOLD_5,
    GOLD_6,
    GOLD_7,

    // Player
    PLAYER_IDLE_LEFT_1,
    PLAYER_IDLE_LEFT_2,
    PLAYER_IDLE_RIGHT_1,
    PLAYER_IDLE_RIGHT_2,
    PLAYER_JUMP_LEFT_1,
    PLAYER_JUMP_LEFT_2,
    PLAYER_JUMP_RIGHT_1,
    PLAYER_JUMP_RIGHT_2,

    // Wiring
    CRATE,
    WOODEN_PLATE,
    WOODEN_PLATE_PRESSED,
    STEEL_PLATE,
    STEEL_PLATE_PRESSED,
    GOLD_PLATE,
    GOLD_PLATE_PRESSED,
    LAMP_LED_OFF,
    LAMP_LED_ON,

    // Door
    DOOR_UP,
    DOOR_DOWN,
    DOOR_LEFT,
    DOOR_RIGHT,

    // UI
    SHIELD_SMALL_HALF,
    SHIELD_SMALL_FULL,
    HEART_SMALL_EMPTY,
    HEART_SMALL_HALF,
    HEART_SMALL_FULL,
    SHIELD_HALF,
    SHIELD_FULL,
    HEART_EMPTY,
    HEART_HALF,
    HEART_FULL,
    ITEM_FRAME,
    ITEM_FRAME_SELECTED,
    GOLD_COIN,

    // Other
    SIGN,
    EFFECT_SLOWED,
    EFFECT_STUNNED,
    EFFECT_BURNING,

    // Elements
    SELECTION_MARKER,
    SELECTION_ARROW_LEFT,
    SELECTION_ARROW_RIGHT,
    SLIDER_BODY,
    SLIDER_HEAD,

    // Animations
    ATTACK_CHOP_UP_ANIMATION,
    ATTACK_CHOP_DOWN_ANIMATION,
    ATTACK_CHOP_LEFT_ANIMATION,
    ATTACK_CHOP_RIGHT_ANIMATION,
    ERUPTION_WINDUP_ANIMATION,
    ERUPTION_ANIMATION,
    ZOMBIE_SMALL_SPAWN_ANIMATION,

    // Items
    WOODEN_SWORD,

    // Barbarian
    BARBARIAN_IDLE_LEFT_1,
    BARBARIAN_IDLE_LEFT_2,
    BARBARIAN_IDLE_RIGHT_1,
    BARBARIAN_IDLE_RIGHT_2,
    BARBARIAN_JUMP_LEFT_1,
    BARBARIAN_JUMP_LEFT_2,
    BARBARIAN_JUMP_RIGHT_1,
    BARBARIAN_JUMP_RIGHT_2,
    BARBARIAN_ATTACK_LEFT_1,
    BARBARIAN_ATTACK_RIGHT_1,

    // Wizard
    WIZARD_IDLE_LEFT_1,
    WIZARD_IDLE_LEFT_2,
    WIZARD_IDLE_RIGHT_1,
    WIZARD_IDLE_RIGHT_2,
    WIZARD_JUMP_LEFT_1,
    WIZARD_JUMP_LEFT_2,
    WIZARD_JUMP_RIGHT_1,
    WIZARD_JUMP_RIGHT_2,
    WIZARD_CASTING_BOLT_LEFT_1,
    WIZARD_CASTING_BOLT_LEFT_2,
    WIZARD_CASTING_BOLT_RIGHT_1,
    WIZARD_CASTING_BOLT_RIGHT_2,
    WIZARD_CASTING_SLOW_LEFT_1,
    WIZARD_CASTING_SLOW_RIGHT_1,
    WIZARD_CASTING_ERUPTION_LEFT_1,
    WIZARD_CASTING_ERUPTION_RIGHT_1,

    // Paladin
    PALADIN_IDLE_LEFT_1,
    PALADIN_IDLE_LEFT_2,
    PALADIN_IDLE_RIGHT_1,
    PALADIN_IDLE_RIGHT_2,
    PALADIN_JUMP_LEFT_1,
    PALADIN_JUMP_RIGHT_1,
    PALADIN_ATTACK_LEFT_1,
    PALADIN_ATTACK_RIGHT_1,
    PALADIN_BLOCKING_LEFT_1,
    PALADIN_BLOCKING_RIGHT_1,
    PALADIN_CHARGING_LEFT_1,
    PALADIN_CHARGING_LEFT_2,
    PALADIN_CHARGING_LEFT_3,
    PALADIN_CHARGING_RIGHT_1,
    PALADIN_CHARGING_RIGHT_2,
    PALADIN_CHARGING_RIGHT_3,

    // Zombie
    ZOMBIE_SMALL_IDLE_LEFT_1,
    ZOMBIE_SMALL_IDLE_LEFT_2,
    ZOMBIE_SMALL_IDLE_RIGHT_1,
    ZOMBIE_SMALL_IDLE_RIGHT_2,
    ZOMBIE_SMALL_JUMP_LEFT_1,
    ZOMBIE_SMALL_JUMP_RIGHT_1,
    ZOMBIE_SMALL_ATTACK_LEFT_1,
    ZOMBIE_SMALL_ATTACK_RIGHT_1,

    // Lich
    LICH_SMALL_IDLE_LEFT_1,
    LICH_SMALL_IDLE_RIGHT_1,
    LICH_SMALL_CASTING_BOLT_LEFT_1,
    LICH_SMALL_CASTING_BOLT_LEFT_2,
    LICH_SMALL_CASTING_BOLT_RIGHT_1,
    LICH_SMALL_CASTING_BOLT_RIGHT_2,
    LICH_SMALL_SPAWNING_ZOMBIE_LEFT_1,
    LICH_SMALL_SPAWNING_ZOMBIE_RIGHT_1,

    // Wraith
    WRAITH_SMALL_IDLE_LEFT_1,
    WRAITH_SMALL_IDLE_RIGHT_1,
    WRAITH_SMALL_MOVE_LEFT_1,
    WRAITH_SMALL_MOVE_RIGHT_1
};